app1/urls.py
"""CUSTOM"""
from django.urls import path
from .views import index, input, export, dataset, predict, importcsv, Downloadpdf
app_name = 'app1'

urlpatterns = [
    path('', index, name = 'index'),
    path('input/', input, name = 'input'),
    path('export/', export, name = 'export'),
    path('dataset/', dataset, name = 'dataset'),
    path('predict/', predict, name = 'predict'),
    path('importcsv/', importcsv, name = 'importcsv'),
    path('pdf_download/',Downloadpdf.as_view(), name = "pdf_download")
]

ckd_pred/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]

app1/models.py
from django.db import models
class Measure(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    weight = models.FloatField()
    gender = models.CharField(max_length=1)
    serum = models.FloatField()
    sg = models.FloatField()
    rbc = models.IntegerField()
    pc = models.IntegerField()
    pcc = models.IntegerField()
    ba = models.IntegerField()
    bgr = models.IntegerField()
    bu = models.IntegerField()
    pot = models.FloatField()
    pcv = models.IntegerField()
    wbcc = models.IntegerField()
    rbcc = models.FloatField()
    htn = models.IntegerField()
    dm = models.IntegerField()
    cad = models.IntegerField()
    pe = models.IntegerField()
    ane = models.IntegerField()
    yclass = models.CharField(max_length=6)
    date_added = models.DateTimeField(auto_now_add=True)

app1/forms.py
from dataclasses import field
from django import forms
from . models import Measure
class MeasureForm(forms.ModelForm):
    class Meta:
        model = Measure
        fields = ['name','age','weight','gender','serum','sg','rbc','pc','pcc','ba','bgr','bu','pot','pcv','wbcc','rbcc','htn','dm','cad','pe','ane','yclass']
        
        labels = {
            'name':'Name',
            'age':'Age (years)',
            'weight': 'Weight',
            'gender':'Gender (M/F)',
            'serum':'Serum Creatinine (μmol/L)',
            'sg':'Specific Gravity (1.005,1.010,1.015,1.020.1.025)',
            'rbc':'Red Blood Cells (Normal:1, abnormal:0)',
            'pc':'Pus Cell (Normal:1, abnormal:0)',
            'pcc':'Pus Cell Clumps (Present:1, Not present:0)',
            'ba':'Bacteria (Present:1, Not present:0)',
            'bgr':'Blood Glucose Random (mgs/dl)',
            'bu':'Blood Urea (mgs/dl)',
            'pot':'Potassium (mEq/L)',
            'pcv':'Packed Cell Volume (numerical)',
            'wbcc':'White Blood Cells Count (cells/cumm)',
            'rbcc':'Red Blood Cells Count (millions/cumm)',
            'htn':'Hypertension (yes:1, no:2)',
            'dm':'Diabetes Mellitus (yes:1, no:2)',
            'cad':'Coronary Artery Disease (yes:1, no:2)',
            'pe':'Pedal Edema (yes:1, no:2)',
            'ane':'Anemia (yes:1, no:2)',
            'yclass':'Patient Condition (ckd/ notckd)'
        }

class PredictForm(forms.ModelForm):
    class Meta:
        model = Measure
        fields = ['name','age','weight','gender','serum','sg','rbc','pc','pcc','ba','bgr','bu','pot','pcv','wbcc','rbcc','htn','dm','cad','pe','ane']
        
        labels = {
            'name':'Name',
            'age':'Age (years)',
            'weight': 'Weight',
            'gender':'Gender (M/F)',
            'serum':'Serum Creatinine (μmol/L)',
            'sg':'Specific Gravity (1.005,1.010,1.015,1.020.1.025)',
            'rbc':'Red Blood Cells (Normal:1, abnormal:0)',
            'pc':'Pus Cell (Normal:1, abnormal:0)',
            'pcc':'Pus Cell Clumps (Present:1, Not present:0)',
            'ba':'Bacteria (Present:1, Not present:0)',
            'bgr':'Blood Glucose Random (mgs/dl)',
            'bu':'Blood Urea (mgs/dl)',
            'pot':'Potassium (mEq/L)',
            'pcv':'Packed Cell Volume (numerical)',
            'wbcc':'White Blood Cells Count (cells/cumm)',
            'rbcc':'Red Blood Cells Count (millions/cumm)',
            'htn':'Hypertension (yes:1, no:2)',
            'dm':'Diabetes Mellitus (yes:1, no:2)',
            'cad':'Coronary Artery Disease (yes:1, no:2)',
            'pe':'Pedal Edema (yes:1, no:2)',
            'ane':'Anemia (yes:1, no:2)',
        }

app1/views.py
import csv
from datetime import date
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Measure
from .forms import MeasureForm, PredictForm
from .randomforest import randomforest_pred
from .calcGFRv2 import main
from io import BytesIO
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views import View
def index(request):
    measures = Measure.objects.order_by('id')
    context = {'measures':measures}
    return render(request, 'app1/index.html',context)

def input(request):
    """Take user input"""
    if request.method != 'POST':
        #no data submitted, return blank form
        form = MeasureForm()
    else:
        #POST data is submittes, process data
        form = MeasureForm(data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('app1:index')
    #display blank or invalid form
    context = {'form':form}
    return render(request,'app1/input.html', context)

def export(request):
    response = HttpResponse(content_type = 'text/csv')
    writer = csv.writer(response)
    writer.writerow(['name','age','gender','serum','sg','rbc','pc','pcc','ba','bgr','bu','pot','pcv','wbcc','rbcc','htn','dm','cad','pe','ane','yclass'])
    for row in Measure.objects.all().values_list('name','age','gender','serum','sg','rbc','pc','pcc','ba','bgr','bu','pot','pcv','wbcc','rbcc','htn','dm','cad','pe','ane','yclass'):
        writer.writerow(row)
    response['Content-Disposition'] = 'attachment; filename="values.csv"'
    return response

def dataset(request):
    measures = Measure.objects.order_by('id')
    context = {'measures':measures}
    return render(request, 'app1/dataset.html',context)

def predict(request):
    """Take user input for prediction"""
    if request.method != 'POST':
        #no data submitted, return blank form
        form = PredictForm()
    else:
        #POST data is submitted, process data
        form = PredictForm(data = request.POST)
        if form.is_valid():
            #form.save(commit=False)
            #return redirect('app1:index')
            """Write func to use form here"""
            dict = form.cleaned_data
            list = [[x for x in dict.values()]]
            ip = [list[0][5:21]]    #input values
            result = randomforest_pred(ip)

            #part2: start
            name = list[0][0]
            age = list[0][1]
            wt = list [0][2]
            gender = list[0][3]
            sc = list[0][4]
            var, mssg = main(gender,age ,sc ,wt)
            #part2: stop
            temp = {'Name':name,'Result':result,'CKD-GFR':var,'Diagnosis': mssg}
            context = {'result':temp}
            return render(request,'app1/result.html',context)
    #display blank or invalid form
    context = {'form':form}
    return render(request,'app1/predict.html', context)
"""
def result(request):
    #measures = Measure.objects.order_by('id')
    #context = {'result':result.dict()}
    temp = {'result':'result'}
    context = {'result':'result'}
    return render(request, 'app1/result.html',context)
"""

def importcsv(request):
    path = 'app1\Datasets\ckd_clean_16_new.csv'
    with open(path) as f:
        reader = csv.reader(f)
        for row in reader:
            _, created = Measure.objects.get_or_create(
                name = row[0],
                age = row[1],
                weight = row[2],
                gender = row[3],
                serum = row[4],
                sg = row[5],
                rbc = row[6],
                pc = row[7],
                pcc = row[8],
                ba = row[9],
                bgr = row[10],
                bu = row[11],
                pot = row[12],
                pcv = row[13],
                wbcc = row[14],
                rbcc = row[15],
                htn = row[16],
                dm = row[17],
                cad = row[18],
                pe = row[19],
                ane = row[20],
                yclass = row[21],
                )
    return HttpResponse('You have added data successfully.')

def renderpdf(template_src, context={}):
    template = get_template(template_src)
    html = template.render(context)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")),result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type = 'application/ppdf')
    return None

data={
    "1":"oje",
    "2":"dfdf",
}

class Downloadpdf(View):
    def get(self,request, *args,**kwargs):
        pdf = renderpdf('app1/result.html',data)
        response =  HttpResponse(pdf,content_type= 'application/pdf')
        #filename = "demo_%s.pdf" %("report")
        #content = "attachment; filename = '%s'" %(filename)
        #response['Content-Disposition'] = content
        response['Content-Disposition'] = 'attachment; filename="report.pdf"'
        return response

app1/templates/app1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Base template</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="style.css">
  <style>
    body {
      background-image: url("{% static 'app1/hospital.png' %}");
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: 100%;
    }
 
  .footer-basic {
  padding:5px 0;
  background-color:#ffffff;
  color:#4b4c4d;
  position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
}

.footer-basic ul {
  padding:0;
  list-style:none;
  text-align:center;
  font-size:18px;
  line-height:1.6;
  margin-bottom:0;
}

.footer-basic li {
  padding:0 10px;
}

.footer-basic ul a {
  color:inherit;
  text-decoration:none;
  opacity:0.8;
}

.footer-basic ul a:hover {
  opacity:1;
}

.footer-basic .social {
  text-align:center;
  padding-bottom:3px;
}

.footer-basic .social > a {
  font-size:20px;
  width:35px;
  height:35px;
  line-height:20px;
  display:inline-block;
  text-align:center;
  border-radius:50%;
  border:1px solid #ccc;
  margin:0 10px;
  color:cadetblue;
  opacity:0.75;
  padding-top: 5px;
}

.footer-basic .social > a:hover {
  opacity:0.9;
}

.footer-basic .copyright {
  margin-top:0px;
  text-align:center;
  font-size:12px;
  color:#aaa;
  margin-bottom:0;
}

/* Credit to https://epicbootstrap.com/snippets/footer-basic */
  </style>
</head>

<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'app1:index' %}"><b>CKD Diagnosis</b></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href=" {% url 'app1:index' %} ">Home</a></li>
    </ul>
    <ul class="nav navbar-nav">
        <li><a href=" {% url 'app1:dataset' %} ">Database</a></li>
    </ul>
    <ul class="nav navbar-nav">
        <li><a href=" {% url 'app1:input' %} ">Register</a></li>
    </ul>
    <ul class="nav navbar-nav">
        <li><a href=" {% url 'app1:export' %} ">Download</a></li>
    </ul>
    <!--
    <ul class="nav navbar-nav">
      <li class="disable"><a href=" {% url 'app1:importcsv' %} ">Import Data</a></li>
    </ul>
  -->
    <ul class="nav navbar-nav">
      <li><a href=" {% url 'app1:predict' %} ">Predict CKD</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <!--<li><a href=" {% url 'app1:pdf_download' %} ">Download CKD</a></li>-->
    </ul>
  </div>
</nav>
  
<div class="container">
  <h3>CKD Diagnostic Center: Keep track of your health here!</h3>
  <hr style="height:2px;border-width:0;color:gray;background-color:cadetblue">
</div>
{% block content %}{% endblock content %}
<div class="footer-basic">
  <footer>
      <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
      <!--
      <ul class="list-inline">
          <li class="list-inline-item"><a href="#">Home</a></li>
          <li class="list-inline-item"><a href="#">Services</a></li>
          <li class="list-inline-item"><a href="#">About</a></li>
          <li class="list-inline-item"><a href="#">Terms</a></li>
          <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
      </ul>
    -->
      <p class="copyright">CKD Prediction Website © 2022</p>
  </footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</div>
</body>
</html>

app1/templates/app1/footer.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Untitled</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="style.css">
    <style>

    </style>
</head>

<body>
    <div class="footer-basic">
        <footer>
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">CKD Prediction Website © 2022</p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</body>

</html>

<!-- credit to https://epicbootstrap.com/snippets/footer-basic -->

app1/templates/app1/index.html
<html>
    <head>
        <title>Home</title>
        <style>
            .about{
                background-color: whitesmoke;
                width: 100%;
                text-align: justify;
                padding: 10px;
                border-style: double;
                border-radius: 10px;
                margin-top: 25px;
                word-spacing: 1.5pt;
                line-height: 2;
            }
            .container{
                background-color: white;
                padding-bottom: 10px;
                
            }
            button{
                padding-left: 25px;
                padding-right: 25px;
                padding-top: 5px;
                padding-bottom: 5px;
                margin-top: 50px;
                border-radius: 5px;
                border-color: white;
                text-align: center;
                background-color: white;
                color: white;
            }
        </style>
    </head>
    <body>
        {% extends "app1/base.html" %}
        {% block content %}
        <div class="container">
        <!--
        <ul>
            {% for measure in measures %}
                <li>{{measure.name}} : {{ measure.age }}</li>
            {% empty %}
                <li>No patient has been added yet.</li>
            {% endfor %}
        </ul>
        -->
        <b>Register here:</b><br>
        <pre><a href ="{% url 'app1:input' %}"><button type="button">Register</button></a></pre>

        <b>Download here:</b><br>
        <pre><a href ="{% url 'app1:export' %}"><button type="button">Download</button></a></pre>

        <b>Start diagnosis:</b><br>
        <pre><a href ="{% url 'app1:predict' %}"><button type="button">Start</button></a></pre>        
        <!--
            <button type="button" onclick="alert('Hello world!')">Click Me!</button>
        -->
        <div class="about" style="color:cadetblue;background-color:whitesmoke;">
            <h3><b><u>About Us</u></b></h3>
                    The diagnosis for the chronic kidney disease (CKD) and the stages of its severity can be done
        using a machine by training it with the patient’s lab reports and allowing it to predict the CKD condition
        using the prior knowledge of the various cases of CKD. The disease is a major issue now-a-days and with
        the help of the CKD prediction system, it will be easier to predict the disease at its early stages to avoid it. The
        illness is commonly diagnosed in the age of range 19-40 and more frequently in ages > 40. Here, the waste
        starts accumulating as the Glomerular Filtration Rate (GFR) decreases overtime, leading to an increase in the
        impurity of the blood. The CKD condition is progressively predominant in patients with CVD or factors such
        as dyslipidaemia, diabetes, hypertension, and metabolic disorder. The CKD prediction system will provide the
        diagnosis which states whether the patient is suffering from the illness or not, also known as the chronic renal
        disease, which is the continuous malfunction of the kidney for months or even years. It is identified based on
        the kidney damage or decrease in the glomerular filtration rate (GFR).<br>
        The disease is increasing rapidly as
        per the studies which conclude that the hospitalization cases
        due to CKD have increased by 6.23 percent per year. And the
        global mortality rate remains fixed. We can help you by providing an instant diagnostic report online.

        </div>
    </div>
    
        {% endblock content %}
    </body>
</html>

app1/templates/app1/input.html
<html>
<head><title>input</title>
    <style>
    form{
        background-color:white;
    }
    pre{
        background-color:black;
    }
    button{
        padding-left: 25px;
        padding-right: 25px;
        padding-top: 5px;
        padding-bottom: 5px;
        margin-top: 50px;
        border-radius: 5px;
        border-color: grey;
        text-align: center;
    }
    .dummy{
        color: transparent;
    }
    .container{
                background-color: white;
                padding-bottom: 10px;
                
            }
</style></head>
<body>
{% extends "app1/base.html" %}
{% block content %}
<div class="container">
<form method="post" action="{% url 'app1:input' %}">
    {% csrf_token %}

    <fieldset>
        <legend>ADD PATIENT DETAILS</legend>
        <pre>
            <label>Name                                            :</label> <input type="text" name="name"/>
        </pre>
        <pre>
            <label>Age (years)                                     :</label> <input type="number" name="age"/>
        </pre>
        <pre>
            <label>Weight (Kilos)                                  :</label> <input type="number" name="weight"/>
        </pre>
        <pre>
            <label>Gender (M/F)                                    :</label> <input type="text" name="gender"/>
        </pre>
        <pre>
            <label>Serum Creatinine (μmol/L)                       :</label> <input type="number" name="serum" step="0.1"/>
        </pre>
        <pre>
            <label>Specific Gravity (1.005,1.010,1.015,1.020.1.025):</label> <input type="number" name="sg" step="0.001"/>
        </pre>
        <pre>
            <label>Red Blood Cells (Normal:1, abnormal:0)          :</label> <input type="number" name="rbc" step="0.1"/>
        </pre>
        <pre>
            <label>Pus Cell (Normal:1, abnormal:0)                 :</label> <input type="number" name="pc" step="0.1"/>
        </pre>
        <pre>
            <label>Pus Cell Clumps (Present:1, Not present:0)      :</label> <input type="number" name="pcc" step="0.1"/>
        </pre>
        <pre>
            <label>Bacteria (Present:1, Not present:0)             :</label> <input type="number" name="ba" step="0.1"/>
        </pre>
        <pre>
            <label>Blood Glucose Random (mgs/dl)                   :</label> <input type="number" name="bgr" step="0.1"/>
        </pre>
        <pre>
            <label>Blood Urea (mgs/dl)                             :</label> <input type="number" name="bu" step="0.1"/>
        </pre>
        <pre>
            <label>Potassium (mEq/L)                               :</label> <input type="number" name="pot" step="0.1"/>
        </pre>
        <pre>
            <label>Packed Cell Volume (numerical)                  :</label> <input type="number" name="pcv" step="0.1"/>
        </pre>
        <pre>
            <label>White Blood Cells Count (cells/cumm)            :</label> <input type="number" name="wbcc" step="0.1"/>
        </pre>
        <pre>
            <label>Red Blood Cells Count (millions/cumm)           :</label> <input type="number" name="rbcc" step="0.1"/>
        </pre>
        <pre>
            <label>Hypertension (yes:1, no:0)                      :</label> <input type="number" name="htn" step="0.1"/>
        </pre>
        <pre>
            <label>Diabetes Mellitus (yes:1, no:0)                 :</label> <input type="number" name="dm" step="0.1"/>
        </pre>
        <pre>
            <label>Coronary Artery Disease (yes:1, no:0)           :</label> <input type="number" name="cad" step="0.1"/>
        </pre>
        <pre>
            <label>Pedal Edema (yes:1, no:0)                       :</label> <input type="number" name="pe" step="0.1"/>
        </pre>
        <pre>
            <label>Anemia (yes:1, no:0)                            :</label> <input type="number" name="ane" step="0.1"/>
        </pre>
        <pre>
            <label>Patient Condition (ckd/ notckd)                 :</label> <input type="text" name="yclass"/>
        </pre>
 
 
        
        <button name = "submit"> SUBMIT </button>
    </fieldset>
</form>
<div class="dummy">
    Terms and conditions*
    Usually, CKD does not give any signs until the kidney is
damaged beyond repair. The disease is increasing rapidly as
per the studies which conclude that the hospitalization cases
due to CKD have increased by 6.23 percent per year. And the
global mortality rate remains fixed. There are few diagnostic
tests to check the condition of CKD such as:
1) eGFR test: It stands for estimated Glomerular Filtration
Rate (eGFR), which analyses the rate of filtration by
glomeruli, present in the kidneys.
2) Urine test: For detecting anomalies in urine that point to
defective kidney functions.
3) Blood tests: For detecting the presence of serum creatinine
or urea in blood.
</div>
</div>
{% endblock content %}
</body>

app1/templates/app1/predict.html
<html>
<head><title>predict</title>
    <style>
    form{
        background-color:white;
    }
    pre{
        background-color:black;
    }
    button{
        padding-left: 25px;
        padding-right: 25px;
        padding-top: 5px;
        padding-bottom: 5px;
        margin-top: 50px;
        border-radius: 5px;
        border-color: grey;
        text-align: center;
    }
    .dummy{
        color: transparent;
    }
    .container{
                background-color: white;
                padding-bottom: 10px;
                
            }
</style></head>
<body>
{% extends "app1/base.html" %}
{% block content %}
<div class="container">
<form method="post" action="{% url 'app1:predict' %}">
    {% csrf_token %}

    <fieldset>
        <legend>PREDICT CKD CONDITION</legend>
        <pre>
            <label>Name                                            :</label> <input type="text" name="name"/>
        </pre>
        <pre>
            <label>Age (years)                                     :</label> <input type="number" name="age"/>
        </pre>
        <pre>
            <label>Weight (Kilos)                                  :</label> <input type="number" name="weight"/>
        </pre>
        <pre>
            <label>Gender (M/F)                                    :</label> <input type="text" name="gender"/>
        </pre>
        <pre>
            <label>Serum Creatinine (μmol/L)                       :</label> <input type="number" name="serum" step="0.1"/>
        </pre>
        <pre>
            <label>Specific Gravity (1.005,1.010,1.015,1.020.1.025):</label> <input type="number" name="sg" step="0.001"/>
        </pre>
        <pre>
            <label>Red Blood Cells (Normal:1, abnormal:0)          :</label> <input type="number" name="rbc" step="0.1"/>
        </pre>
        <pre>
            <label>Pus Cell (Normal:1, abnormal:0)                 :</label> <input type="number" name="pc" step="0.1"/>
        </pre>
        <pre>
            <label>Pus Cell Clumps (Present:1, Not present:0)      :</label> <input type="number" name="pcc" step="0.1"/>
        </pre>
        <pre>
            <label>Bacteria (Present:1, Not present:0)             :</label> <input type="number" name="ba" step="0.1"/>
        </pre>
        <pre>
            <label>Blood Glucose Random (mgs/dl)                   :</label> <input type="number" name="bgr" step="0.1"/>
        </pre>
        <pre>
            <label>Blood Urea (mgs/dl)                             :</label> <input type="number" name="bu" step="0.1"/>
        </pre>
        <pre>
            <label>Potassium (mEq/L)                               :</label> <input type="number" name="pot" step="0.1"/>
        </pre>
        <pre>
            <label>Packed Cell Volume (numerical)                  :</label> <input type="number" name="pcv" step="0.1"/>
        </pre>
        <pre>
            <label>White Blood Cells Count (cells/cumm)            :</label> <input type="number" name="wbcc" step="0.1"/>
        </pre>
        <pre>
            <label>Red Blood Cells Count (millions/cumm)           :</label> <input type="number" name="rbcc" step="0.1"/>
        </pre>
        <pre>
            <label>Hypertension (yes:1, no:0)                      :</label> <input type="number" name="htn" step="0.1"/>
        </pre>
        <pre>
            <label>Diabetes Mellitus (yes:1, no:0)                 :</label> <input type="number" name="dm" step="0.1"/>
        </pre>
        <pre>
            <label>Coronary Artery Disease (yes:1, no:0)           :</label> <input type="number" name="cad" step="0.1"/>
        </pre>
        <pre>
            <label>Pedal Edema (yes:1, no:0)                       :</label> <input type="number" name="pe" step="0.1"/>
        </pre>
        <pre>
            <label>Anemia (yes:1, no:0)                            :</label> <input type="number" name="ane" step="0.1"/>
        </pre>
        
      <button name = "submit"> PREDICT </button>  
    </fieldset>
    
</form>


<div class="dummy">
    Terms and conditions*
    Usually, CKD does not give any signs until the kidney is
damaged beyond repair. The disease is increasing rapidly as
per the studies which conclude that the hospitalization cases
due to CKD have increased by 6.23 percent per year. And the
global mortality rate remains fixed. There are few diagnostic
tests to check the condition of CKD such as:
1) eGFR test: It stands for estimated Glomerular Filtration
Rate (eGFR), which analyses the rate of filtration by
glomeruli, present in the kidneys.
2) Urine test: For detecting anomalies in urine that point to
defective kidney functions.
3) Blood tests: For detecting the presence of serum creatinine
or urea in blood.
</div>
</div>
{% endblock content %}
</body>